use_field_init_shorthand = true
imports_granularity = "Crate"
wrap_comments = true
group_imports = "StdExternalCrate"
edition = "2021"
reorder_impl_items = true
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_strings = true
max_width = 80
